# Chave da API do Google
google_api_key = "AIzaSyCHfDFrx0HtEOaDz5I9oMJXnlDh70a7osc"

# Chave da API do Groq
groq_api_key = "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"

# 103354810749107216062